#!/usr/bin/env python3
# Generated by pysed2translate from calculations.sed2.json (backend: roadrunner).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'roadrunner'
PREFIX = 'calculations'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {
    'a': [1, 2, 3],
    'b': 2,
    'sep': '-',
}

def run(ctx):
    task_c = rt.m.to_data(rt.m.add(1.0, rt.m.mul(rt.AnnotatedData.from_constant(CONSTANTS['a']), rt.AnnotatedData.from_constant(CONSTANTS['b']))))
    task_total = rt.m.to_data(rt.m.div(rt.m.sum(task_c), 3.0))
    task_blk = rt.ops.block(['first', 'second'], [task_c, rt.AnnotatedData.from_constant(CONSTANTS['a'])])
    task_lab = rt.ops.relabel(rt.AnnotatedData.from_constant(CONSTANTS['a']), ['x', 'y', 'z'])
    task_txt = rt.ops.string_formation(['n', rt.AnnotatedData.from_constant(CONSTANTS['sep']), task_total])
    with ctx.step('c'):
        rt.write_report(ctx, 'c', task_c)
    with ctx.step('total'):
        rt.write_report(ctx, 'total', task_total)
    with ctx.step('blk'):
        rt.write_report(ctx, 'blk', task_blk)
    with ctx.step('lab'):
        rt.write_report(ctx, 'lab', task_lab)
    with ctx.step('txt'):
        rt.write_report(ctx, 'txt', task_txt)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except rt.BackendCannotRun as e:  # the simulator cannot run this model: a skip, not a result
        print(f'skip: {BACKEND} cannot run the model: {e}', file=sys.stderr)
        return rt.EXIT_CANNOT_RUN
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
