#!/usr/bin/env python3
# Generated by pysed2translate from constants_reports.sed2.json (backend: copasi).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'copasi'
PREFIX = 'constants_reports'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {
    'x': 3,
    'vec': [1, 2, 3],
    'grid': [[1, 2], [3, 4]],
    'names': ['a', 'b'],
    'labelled': {'p': 1, 'q': 2},
}

def run(ctx):
    with ctx.step('scalar'):
        rt.write_report(ctx, 'scalar', rt.AnnotatedData.from_constant(CONSTANTS['x']))
    with ctx.step('vector'):
        rt.write_report(ctx, 'vector', rt.AnnotatedData.from_constant(CONSTANTS['vec']))
    with ctx.step('slice'):
        rt.write_report(ctx, 'slice', rt.AnnotatedData.from_constant(CONSTANTS['vec']).index([[('range', (1, None))]]))
    with ctx.step('cell'):
        rt.write_report(ctx, 'cell', rt.AnnotatedData.from_constant(CONSTANTS['grid']).index([[('int', 1), ('int', 0)]]))
    with ctx.step('names'):
        rt.write_report(ctx, 'names', rt.AnnotatedData.from_constant(CONSTANTS['names']))
    with ctx.step('keyed'):
        rt.write_report(ctx, 'keyed', rt.AnnotatedData.from_constant(CONSTANTS['labelled']).index([[('label', 'q')]]))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except rt.BackendCannotRun as e:  # the simulator cannot run this model: a skip, not a result
        print(f'skip: {BACKEND} cannot run the model: {e}', file=sys.stderr)
        return rt.EXIT_CANNOT_RUN
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
