#!/usr/bin/env python3
# Generated by pysed2translate from csv_import.sed2.json (backend: copasi).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'copasi'
PREFIX = 'csv_import'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {}

def run(ctx):
    task_d = rt.ops.csv_import(ctx.input_path('data.csv'), separator=None, headers=True, column_names=None, ncols=None, nrows=None)
    task_col = rt.m.to_data(rt.m.mul(1.0, task_d.index([[('range', (0, 3)), ('int', 1)]])))
    with ctx.step('table'):
        rt.write_report(ctx, 'table', task_d)
    with ctx.step('col'):
        rt.write_report(ctx, 'col', task_col)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except rt.BackendCannotRun as e:  # the simulator cannot run this model: a skip, not a result
        print(f'skip: {BACKEND} cannot run the model: {e}', file=sys.stderr)
        return rt.EXIT_CANNOT_RUN
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
