#!/usr/bin/env python3
# Generated by pysed2translate from fba.sed2.json (backend: cobra).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'cobra'
PREFIX = 'fba'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {}

def run(ctx):
    task_m = rt.SbmlModel.load(ctx.input_path('toy_fba.xml'), 'urn:sedml:language:sbml')
    task_base, task_base_model = rt.backends.get(BACKEND).fba(task_m, rt.backends.FbaRequest(output_variables=['R_BIOMASS', 'R_RESP'], algorithm='KISAO:0000437'))
    rep_points_sc = rt.ops.numbers_from(rt.AnnotatedData.from_constant([-10, -5]))
    rep_rows_sc = []
    for rep_i_sc, rep_value_sc in enumerate(rep_points_sc):
        rep_range_sc = rt.AnnotatedData(rep_value_sc)
        rep_index_sc = rt.AnnotatedData(float(rep_i_sc))
        task_sc_subTasks_c = task_m.with_values({'R_EX_glc_lower_bound': rt.ops.scalar(rep_range_sc)})
        task_sc_subTasks_f, task_sc_subTasks_f_model = rt.backends.get(BACKEND).fba(task_sc_subTasks_c, rt.backends.FbaRequest(output_variables=['R_BIOMASS'], algorithm=None))
        rep_rows_sc.append([task_sc_subTasks_f.index([[('label', 'R_BIOMASS')]])])
    task_sc = rt.ops.repeat_table(rep_points_sc, rep_rows_sc, ['G'])
    with ctx.step('r_base'):
        rt.write_report(ctx, 'r_base', task_base)
    with ctx.step('r_scan'):
        rt.write_report(ctx, 'r_scan', task_sc)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except rt.BackendCannotRun as e:  # the simulator cannot run this model: a skip, not a result
        print(f'skip: {BACKEND} cannot run the model: {e}', file=sys.stderr)
        return rt.EXIT_CANNOT_RUN
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
