#!/usr/bin/env python3
# Generated by pysed2translate from ode_time_courses.sed2.json (backend: roadrunner).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'roadrunner'
PREFIX = 'ode_time_courses'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {
    'tol': 1e-08,
}

def run(ctx):
    task_m = rt.SbmlModel.load(ctx.input_path('model.xml'), 'urn:sedml:language:sbml')
    task_explicit, task_explicit_model = rt.backends.get(BACKEND).time_course(task_m, rt.backends.TimeCourse(independent_variable='time', output_variables=['S1', 'S2'], points=rt.ops.numbers_from(rt.ops.numeric_range(start=0.0, end=4.0, number_of_steps=4.0)), settings={'relativeTolerance': rt.ops.scalar(rt.AnnotatedData.from_constant(CONSTANTS['tol'])), 'maxNumberOfSteps': 5000}, algorithm=None))
    task_one, task_one_model = rt.backends.get(BACKEND).time_course(task_explicit_model, rt.backends.TimeCourse(independent_variable='time', output_variables=['S1'], start=1.0, step=2.0, settings={}, algorithm=None))
    with ctx.step('traj'):
        rt.write_report(ctx, 'traj', task_explicit)
    with ctx.step('step'):
        rt.write_report(ctx, 'step', task_one)
    with ctx.step('s1'):
        rt.write_report(ctx, 's1', task_explicit.index([[('range', (0, 5)), ('label', 'S1')]]))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
