#!/usr/bin/env python3
# Generated by pysed2translate from plots.sed2.json (backend: roadrunner).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'roadrunner'
PREFIX = 'plots'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {
    't': [0, 1, 2, 3],
    'y': [1, 4, 9, 16],
    'gx': [0, 1],
    'gy': [0, 1, 2],
    'z': [[1, 2, 3], [4, 5, 6]],
}

def run(ctx):
    with ctx.step('p'):
        rt.plots.plot2d(ctx, 'p', [{'id': 'c', 'position': 0, 'type': 'points', 'order': 1, 'y_axis': None, 'fields': {'x': rt.AnnotatedData.from_constant(CONSTANTS['t']), 'y': rt.AnnotatedData.from_constant(CONSTANTS['y'])}}], {'axes': {'x': {'scale': 'linear'}, 'y': {'scale': 'log10'}}, 'legend': True, 'width': None, 'height': None})
    with ctx.step('q'):
        rt.plots.plot3d(ctx, 'q', [{'id': 's', 'position': 0, 'type': 'heatMap', 'order': None, 'fields': {'x': rt.AnnotatedData.from_constant(CONSTANTS['gx']), 'y': rt.AnnotatedData.from_constant(CONSTANTS['gy']), 'z': rt.AnnotatedData.from_constant(CONSTANTS['z'])}}], {'axes': {}, 'legend': None, 'width': None, 'height': None})
    with ctx.step('r'):
        rt.write_report(ctx, 'r', rt.AnnotatedData.from_constant(CONSTANTS['y']))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
