#!/usr/bin/env python3
# Generated by pysed2translate from repeats.sed2.json (backend: roadrunner).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'roadrunner'
PREFIX = 'repeats'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {}

def run(ctx):
    task_m = rt.SbmlModel.load(ctx.input_path('model.xml'), 'urn:sedml:language:sbml')
    rep_points_sc = rt.ops.numbers_from(rt.ops.numeric_range(start=0.25, interval=0.25, number_of_steps=3.0))
    rep_rows_sc = []
    for rep_i_sc, rep_value_sc in enumerate(rep_points_sc):
        rep_range_sc = rt.AnnotatedData(rep_value_sc)
        rep_index_sc = rt.AnnotatedData(float(rep_i_sc))
        task_sc_subTasks_c = task_m.with_values({'k1': rt.ops.scalar(rep_range_sc)})
        task_sc_subTasks_s, task_sc_subTasks_s_model = rt.backends.get(BACKEND).time_course(task_sc_subTasks_c, rt.backends.TimeCourse(independent_variable='time', output_variables=['S1'], step=2.0, settings={}, algorithm=None))
        rep_rows_sc.append([task_sc_subTasks_s.index([[('label', 'S1')]])])
    task_sc = rt.ops.repeat_table(rep_points_sc, rep_rows_sc, ['S1'])
    rep_points_lp = rt.ops.numbers_from(rt.ops.numeric_range(start=1.0, interval=1.0, number_of_steps=3.0))
    rep_rows_lp = []
    loopvar_lp_loopVariables_acc = rt.AnnotatedData.from_constant(1.0)
    for rep_i_lp, rep_value_lp in enumerate(rep_points_lp):
        rep_range_lp = rt.AnnotatedData(rep_value_lp)
        rep_index_lp = rt.AnnotatedData(float(rep_i_lp))
        task_lp_subTasks_d = rt.m.to_data(rt.m.mul(rt.m.mul(1.0, loopvar_lp_loopVariables_acc), 2.0))
        rep_rows_lp.append([task_lp_subTasks_d])
        loopvar_lp_loopVariables_acc = task_lp_subTasks_d
    task_lp = rt.ops.repeat_table(rep_points_lp, rep_rows_lp, ['D'])
    rep_names_ps = ['k1', 'S1']
    rep_ranges_ps = [rt.ops.numbers_from(rt.ops.numeric_range(start=0.25, interval=0.25, number_of_steps=2.0)), rt.ops.numbers_from(rt.ops.numeric_range(values=[1.0, 2.0]))]
    rep_rows_ps = []
    for rep_ix_ps in rt.ops.grid([len(r) for r in rep_ranges_ps]):
        rep_vals_ps = [r[k] for r, k in zip(rep_ranges_ps, rep_ix_ps)]
        rep_model_ps = task_m.with_values(dict(zip(rep_names_ps, rep_vals_ps)))
        rep_ranges_now_ps = rt.ops.labeled_vector(rep_names_ps, rep_vals_ps)
        rep_indexes_now_ps = rt.ops.labeled_vector(rep_names_ps, [float(k) for k in rep_ix_ps])
        task_ps_subTasks_s, task_ps_subTasks_s_model = rt.backends.get(BACKEND).time_course(rep_model_ps, rt.backends.TimeCourse(independent_variable='time', output_variables=['S1'], step=1.0, settings={}, algorithm=None))
        rep_rows_ps.append([task_ps_subTasks_s.index([[('label', 'S1')]])])
    task_ps = rt.ops.scan_table(rep_rows_ps, rep_ranges_ps, rep_names_ps, ['S1'])
    rep_points_sc2 = rt.ops.numbers_from(rt.AnnotatedData.from_constant([10, 20, 30]))
    rep_rows_sc2 = []
    for rep_i_sc2, rep_value_sc2 in enumerate(rep_points_sc2):
        rep_range_sc2 = rt.AnnotatedData(rep_value_sc2)
        rep_index_sc2 = rt.AnnotatedData(float(rep_i_sc2))
        task_sc2_subTasks_x = rt.m.to_data(rt.m.add(rt.m.mul(1.0, rep_range_sc2), 1.0))
        rep_rows_sc2.append([task_sc2_subTasks_x])
    task_sc2 = rt.ops.repeat_table(rep_points_sc2, rep_rows_sc2, ['X'])
    with ctx.step('scatter'):
        rt.write_report(ctx, 'scatter', task_sc)
    with ctx.step('loop'):
        rt.write_report(ctx, 'loop', task_lp)
    with ctx.step('scan'):
        rt.write_report(ctx, 'scan', task_ps)
    with ctx.step('one'):
        rt.write_report(ctx, 'one', task_ps.index([[('int', 1), ('int', 0)]]))
    with ctx.step('values'):
        rt.write_report(ctx, 'values', task_sc2)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
