#!/usr/bin/env python3
# Generated by pysed2translate from steady_state_jacobian.sed2.json (backend: roadrunner).
# Do not edit: regenerate from the SED2 document instead.
"""Run the simulation experiment and write its report files."""
import argparse
import os
import sys
import traceback

from pysed2translate import runtime as rt

BACKEND = 'roadrunner'
PREFIX = 'steady_state_jacobian'
DEFAULT_INPUT_DIR = None
DEFAULT_OUTPUT_DIR = None

CONSTANTS = {}

def run(ctx):
    task_m = rt.SbmlModel.load(ctx.input_path('model.xml'), 'urn:sedml:language:sbml')
    task_ss, task_ss_model = rt.backends.get(BACKEND).steady_state(task_m, rt.backends.SteadyState(independent_variable='time', output_variables=['S1', 'S2'], algorithm=None))
    task_jf = rt.backends.get(BACKEND).jacobian(task_ss_model, reduced=False)
    task_jr = rt.backends.get(BACKEND).jacobian(task_m, reduced=True)
    task_els = rt.ops.string_data(task_m.element_ids(include_elements=None, include_types=['species'], exclude_elements=None, exclude_types=None))
    with ctx.step('ss'):
        rt.write_report(ctx, 'ss', task_ss)
    with ctx.step('jf'):
        rt.write_report(ctx, 'jf', task_jf)
    with ctx.step('jr'):
        rt.write_report(ctx, 'jr', task_jr)
    with ctx.step('els'):
        rt.write_report(ctx, 'els', task_els)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--input-dir', default=DEFAULT_INPUT_DIR or os.path.dirname(os.path.abspath(__file__)),
                    help='directory that relative model and data locations are resolved against')
    ap.add_argument('--output-dir', default=DEFAULT_OUTPUT_DIR or '.',
                    help='directory the result files are written to')
    ap.add_argument('--no-png', action='store_true', help='do not draw pictures of the plots')
    ap.add_argument('--manifest', metavar='FILE', help='also write a JSON description of the files written')
    args = ap.parse_args(argv)
    ctx = rt.Context(args.input_dir, args.output_dir, PREFIX, png=not args.no_png)
    try:
        run(ctx)
    except Exception:  # a failed task stops the experiment
        traceback.print_exc()
        return 1
    finally:
        if args.manifest:
            ctx.write_manifest(args.manifest)
    return ctx.exit_status()


if __name__ == '__main__':
    sys.exit(main())
